name: admin-ui-jitsi-meet
namespace: mickael
version: 0.1.0
author: Mickael HUBERT
display_name: Jitsi Meet
tags:
  - beta
  - application
homepage: https://github.com/Mickaelh51/wazo-admin-ui-jitsi-meet
debian_depends:
  - python-jwt
